config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products

  resource :cart, only: [ :show ] do
    post "add", path: "add/:id"#, on: :member
    get  :checkout
  end

  resources :orders, only: [:index, :show, :create]

  root 'products#index'

end

app/models/cart.rb
class Cart 

	attr_reader :items

	def self.build_from_hash hash #build a cart item from the items hash (this hash represents the session)
		items = if hash["cart"] then #check if the cart is actually there
			hash["cart"]["items"].map do |item_data| 
			CartItem.new item_data["product_id"], item_data["quantity"]
		end
		else
			[] #otherwise (if the hash cart does not exist) return an empty array
		end

		new items
	end

	def initialize items = [] # initialize the cart with an items array. It is in this array that all the items will be put.
		@items = items #the global variable @items will have the value of the items array
	end


	def add_item product_id

		item = @items.find{ |item| item.product_id == product_id } # find an item with the same product_id as the one being added
		if item # if that item is found...
			item.increment # increment the quantity of the product in the catItem 
			# puts "testing"
		else #if it's not there ...
			@items << CartItem.new(product_id) # create a cartItem and add it to the items array.
			#  puts "nice"
		end
	end

	def count
		@items.length
	end

	def empty?
		@items.empty?
	end

	def serialize #creates an items hash from the items array

		items = @items.map do |item| #we have to iterate through the array, each array item will be stored in the variable item
			{
				"product_id" => item.product_id,  #now create a hash key "product_id" with the value in item called product_id
				"quantity" => item.quantity       #and a key called "quantity" with the value item.quantity
			}
		end 

		

		{
			
			"items" => items  #add the items into the cart
			
		}
		
	end

	def total_price
		@items.inject(0) { |sum, item| sum + item.total_price } # the inject method initializes sum to 0 so 0 + item.price
		#the iterator will go through all the items in teh cart
	end
end

app/models/cart_item.rb
class CartItem

	attr_reader :product_id, :quantity

	def initialize product_id, quantity = 1
		@product_id = product_id
		@quantity   = quantity
		
	end

	def increment
		@quantity = @quantity + 1
	end

	def product
		 Product.find product_id
	end

	def total_price
		product.price * quantity
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items
end

app/models/order_form.rb
class OrderForm
	include ActiveModel::Model # Enable the order form to include the form_for helper method

	#the order form is a form object that will contain information  from more than one model, more than one object

	attr_accessor :user, :order #credit_cart
	attr_writer :cart # we need to do this so we can pass it into a constructor build_order_items

	def save
		set_password_for_user

		if valid?
			persist
			true
		else
			false
		end
	end

	def has_errors?
		user.errors.any?
	end

	private

	def valid?
		user.valid?
	end

	def persist
		user.save
		@order = Order.create! user: user #now lets create a new order as we save the user

		build_order_items
	end

	def set_password_for_user
		user.password = Digest::SHA1.hexdigest(user.email + Time.now.to_s)[0..8] #creae a password using SHA1 Module with a digest using the first 8 characters of their email
	end

	def build_order_items
		@cart.items.each do |item|
			@order.order_items.create! product_id: item.product_id, quantity: item.quantity #this will run several times depending on the number of items in the cart
		end
	end


end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :image, ImageUploader #mount an  uploaser called image, of  refereing to ImageUploader

	validates_presence_of :name, :price #ensures that these two are inputed
	validates_numericality_of :price  # makes price a number
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name, :address, :city, :country, :postal_code
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def initialize_cart
  	@cart = Cart.build_from_hash session
  	#session variable always exists in each different controller
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_filter :initialize_cart

	def add 
		@cart.add_item params[:id] # add the item to the cart
		session["cart"] = @cart.serialize # update the cart item in the session variable/hash
		product = Product.find params[:id]
		redirect_to :back, notice: "Added #{product.name} to cart."
	end

	def show
	end

	def checkout
		@order_form = OrderForm.new user: User.new #this is an order form object that uses Active Model to recieve (informstion)parameters from outside
	end
end

app/controllers/orders_controller.rb
class  OrdersController < ApplicationController
	before_filter :initialize_cart # very important. to create anorder we need the information in the cart

	def create
		@order_form = OrderForm.new(
			user: User.new( order_params[:user] ),
			cart: @cart # we need the cart inorder to process the order. so we pass an instance variable, because we already initialized the cart
			)

		if @order_form.save
			redirect_to root_path, notice: "Thank you for placing your order."
		else
			render "carts/checkout" # make sure to return the the checkout page if it doesn't save
		end

	end

	


	private

	def order_params
		params.require(:order_form).permit(
			user: [:name, :phone, :address, :city, :country, :postal_code, :email]
			)
	end

	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :initialize_cart
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/application/_cart.html.haml
-if @cart #if the cart exists
	%p.navbar-text.navbar-right
		=if @cart.empty? #chek if it is empty
			Your cart is empty
		-else
			-link_to "You have #{pluralize @cart.count, "item"}.", cart_path

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Woodvale Office Suites</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Products', products_path %></li>
      </ul>
      <%= render 'cart'%>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/carts/checkout.html.haml
%h1 Checkout

%h2 You are checking out with the following products:

%ul
	-@cart.items.each do |item|
		%li
			%em=item.quantity
			=item.product.name
			=item.total_price

%p
	%stromg
		Total Price:
		=number_to_currency @cart.total_price

=form_for @order_form, url: orders_path do |f|
	=render "orders/errors"

	%h3 Some of your personal details
	=f.fields_for :user, f.object.user do |u|
		.form-group
			%p=u.text_field :name, placeholder: "Name", class: "form-control input-lg"
			%p
				=u.text_field :email, placeholder: "Email", class: "form-control"
				%span.help-block This will help you track your order more effectively.
		.from-group
			.row
				%P.col-md-6=u.text_field :address, placeholder: "Address", class: "form-control"
				%p.col-md-3=u.text_field :postal_code, placeholder: "Posta code / Zip code", class: "form-control"
				%p.col-md-3=u.text_field :city, placeholder: "City", class: "form-control"
			%p=u.country_select :country, { priority_countries: [ "KE", "GB", "US", "DE", "ES", "PT"]}, {class: "form-control"}
			%p=u.text_field :phone , class: "form-control", placeholder: "Phone"

	%p=f.submit "Place Order", class: "btn btn-primary"

app/views/carts/show.html.haml
%h1 Your Cart

%table.table.table-hover
	%thead
		%tr
			%th Quantity
			%th Product
			%th Price
		-@cart.items.each do |item|
			%tr
				%td=item.quantity
				%td
					=image_tag item.product.image.thumb
					=link_to item.product.name, item.product
				%td=item.total_price

%p=@cart.total_price

%p=link_to "Checkout", checkout_cart_path, class: "btn btn-primary"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'nav' %>
<div class='container'>
	<%= content_tag :div, notice, class: "bg-success"%>
	<%= content_tag :div, alert, class: "bg-danger"%>
	<%= yield %>
</div>

</body>
</html>

app/views/orders/_errors.html.haml
-if @order_form.has_errors?
	.panel.panel-danger
		.panel-heading
			%h4.panel-title We have found some problems with your data, Please review them.
		.panel-body
			-@order_form.user.errors.full_messages.each do |error|
				%p
					%strong User:
					=error

app/views/products/_form.html.haml
= form_for @product, multipart: true do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Products

%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Price
      %th Image
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.name, product
        %td= number_to_currency product.price
        %td= image_tag product.image.thumb
        %td
          = link_to 'Edit', edit_product_path(product)
          = link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

%p= link_to 'New Product', new_product_path, class: "btn btn-primary"  

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%h1= @product.name

%p= @product.price

%p= image_tag @product.image, height: "300"

%p=link_to "Add to Cart", add_cart_path, method: :post, class: "btn btn-primary"

%p
	= link_to 'Edit', edit_product_path(@product)
	\|
	= link_to 'Back', products_path